plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
	id 'java'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"autocrafters" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	runs {
		create("testServer") {
			server()

			name "Test Minecraft Server"
			vmArg "-Dfabric-api.gametest"
			runDir "run/saves"
			source sourceSets.test
		}

		create("testClient") {
			client()

			name "Test Minecraft Client"
			programArgs "--quickPlaySingleplayer", "world"
			programArgs "--username", "DEV"
			source sourceSets.test
		}
	}
}

sourceSets {
	test {
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath

		compileClasspath += client.compileClasspath
		runtimeClasspath += client.runtimeClasspath
	}
}

runTestClient {
	dependsOn.add(runTestServer)
}

repositories {
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

processTestResources {
	dependsOn.add(processResources)
	from("build/resources/test") {
		duplicatesStrategy = DuplicatesStrategy.INCLUDE
		into "../main"
	}
	from("build/resources/main") {
		duplicatesStrategy = DuplicatesStrategy.INCLUDE
		into "../test"
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

test {
	dependsOn.add(runTestServer)
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName" }
	}
}
